name: Build

on:
  pull_request:
    branches:
      - main
      - develop
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup node 28
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install deps
        run: yarn

      - name: Lint app
        run: yarn lint

      - name: Build app
        run: yarn build